### ISSUE TITLE
Implement 'Not connected' or 'Connection error' screen

### ISSUE THREAD

**Issue by kwingram25** [paritytech/contracts-ui#101]
If not connected to a chain or there was an error, display better message and prompt to check endpoint status and/or switch to a different endpoint. Exists already for original ui

Design needed @erler

**Comment by erler** [comment]
![Home - Not Connected](https://user-images.githubusercontent.com/7072141/141820121-b0b09ec5-de79-4250-bd03-4474dbe087b1.png)
