### ISSUE TITLE
Enhance contract page header

### ISSUE THREAD

**Issue by kwingram25** [paritytech/contracts-ui#129]
- Should display copyable address and identicon
- Should allow editing contract display name if owner is viewing

**Comment by erler** [comment]
<img width="418" alt="Screenshot 2021-12-06 at 17 39 56" src="https://user-images.githubusercontent.com/7072141/144885969-ff7f5ea5-e17a-43de-89b6-a710abcedfac.png">
<img width="408" alt="Screenshot 2021-12-06 at 17 40 40" src="https://user-images.githubusercontent.com/7072141/144885983-4d58bcb4-f809-45c9-9e1e-ac5e9a1ae994.png">

We were wondering in the design guild how many users know that the identicon also functions as a way to copy the address. If we have a standard copy icon next to it, that might be more friendly for new users in the ecosystem.
