### ISSUE TITLE
Dry run instantiate

### ISSUE THREAD

**Issue by athei** [paritytech/contracts-ui#132]
AFAIK sce already dry-runs `call` as RPC in order to determine the gas limit and error state. The same should be done for `instantiate` and `instantiate_with_code`.

https://github.com/polkadot-js/apps/issues/5338

**Comment by cmichi** [comment]
Just FYI, these are the GitHub issues for the other UI's:

* https://github.com/paritytech/canvas-ui/issues/108
* https://github.com/polkadot-js/apps/issues/5338

This whole thing is still an annoying problem and we regularly have users stumble on this (like in https://github.com/paritytech/substrate-contracts-node/issues/13).
