### ISSUE TITLE
Show debug message to user

### ISSUE THREAD

**Issue by athei** [paritytech/contracts-ui#134]
https://github.com/polkadot-js/apps/issues/6466

**Comment by statictype** [comment]
we might already have this, but no examples to try it with

**Comment by athei** [comment]
You mean because the debug buffer is always empty? Try [this contract](https://github.com/paritytech/ink/blob/master/examples/contract-transfer/lib.rs). It has some `debug_println` in it. You could also just add a `debug_println` to the flipper contract and test with that.

You need to make sure to compile without `--release`. Otherwise all debug messages are stripped.
