### ISSUE TITLE
Editable contract name

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#140]
Users should be able to rename the contracts they instantiate, but not other contracts. 

not clear how you get to the "edit contract name" page in Figma. if it's by clicking on the contract name in the header, why not edit in place? @erler

**Comment by erler** [comment]
In my head I had this button to edit contract info, but if it's only the name it makes sense to edit in place.
<img width="538" alt="Screenshot 2021-11-15 at 17 07 17" src="https://user-images.githubusercontent.com/7072141/141814775-8319d091-56be-4dd1-b24d-69b19f3fdef8.png">

**Comment by statictype** [comment]
duplicate of https://github.com/paritytech/contracts-ui/issues/129
