### ISSUE TITLE
Add warning for instantiating contract above size limit

### ISSUE THREAD

**Issue by kwingram25** [paritytech/contracts-ui#154]
When trying to instantiate a contract above a recommended file size, allow user to proceed but display a warning message (design needed?)

**Comment by erler** [comment]
<img width="389" alt="Screenshot 2021-11-24 at 14 55 53" src="https://user-images.githubusercontent.com/7072141/143251619-06da0333-65ec-4e32-9971-40e8eba0f127.png">

As we don't have a hard limit, I guess a warning message is sufficient.

**Comment by peetzweg** [comment]
What is the "recommended file size", where do we get it from and is it chain specific? 🤔

**Comment by statictype** [comment]
this was an old idea, before the contract sizes were reduced. i don't think it makes sense anymore
