### ISSUE TITLE
Use a uniform Layout template all over the App

### ISSUE THREAD

**Issue by achimcc** [paritytech/contracts-ui#179]
This is how the Contracts page looks like on a ultrawide screen:

![contracts_page](https://user-images.githubusercontent.com/16603991/148808081-eef5292b-3e9f-44f0-8b91-fda88d02dfa0.png)

And this is how the instantiate screen looks like on an ultrawide screen:

![instantiate_screen](https://user-images.githubusercontent.com/16603991/148808325-efad6621-1d5f-49c7-9e24-6e3e01f44840.png)

While the issue is less severe on smaller screens the jump of the position of the right column and the amount of space occupied by the middle column is a bit confusing there as well.

We should use the same three column layout pattern for all pages all over the app to provide a uniform experience.

**Comment by statictype** [comment]
<img width="2336" alt="Screenshot 2023-03-20 at 23 14 52" src="https://user-images.githubusercontent.com/42985153/228534707-7aa1c5e1-8332-4cc6-89b2-485019b10523.png">
<img width="2286" alt="Screenshot 2023-03-20 at 23 15 21" src="https://user-images.githubusercontent.com/42985153/228534714-875ad7a8-e330-46bc-b92f-f4fdef09a312.png">

**Comment by statictype** [comment]
there are misalignments if you look at the lines
