### ISSUE TITLE
No way to unlock key pair

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#181]
When i try to use an account that is not a development account, i get a signing error
To unlock the account, the user needs to input the password through polkadot.js extension

<img width="864" alt="Screenshot 2022-01-12 at 13 25 33" src="https://user-images.githubusercontent.com/42985153/149140317-0b316b68-dfda-4ec9-89fd-ba0714ccad0e.png">

**Comment by deep-ink-ventures** [comment]
I still have this problem. I'm not using a local node but connect by adding a custom `?rpc` param.

**Comment by statictype** [comment]
please provide the custom rpc you are using in order to reproduce

**Comment by deep-ink-ventures** [comment]
I use `https://contracts-ui.substrate.io/?rpc=wss://node.genesis-dao.org` and e.g. 5C4yDqMhcYCBtNxYDLMYmQ3VKatEYq5MEteCWh2V3SfnBzcs has this problem (ALICE has tokens to play with).

This is the source: https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/contracts/extensions/dao-assets-contract/src/lib.rs
