### ISSUE TITLE
Instantiate/call dry run results display

### ISSUE THREAD

**Issue by kwingram25** [paritytech/contracts-ui#184]
User should be able to dry-run call or instantiate with the current values and view potential outcome, including
- Gas consumed
- Storage deposit refund or charge
- Success or failure and any errors returned
- Debug message

Design needed

**Comment by erler** [comment]
Styled outcome prediction card
![Upload - Step 3](https://user-images.githubusercontent.com/7072141/153591828-e97ac1ce-9028-45c9-beb9-efd1dbeaebbc.png)

**Comment by kwingram25** [comment]
Nice! I should have been clear the Charge is actually the storage deposit which can also be a Refund. So we can change the label and maybe color code for which of the two it is. Also, there are different errors that can come back which we're now intercepting, OutOfGas, StorageDepositLimitExhausted, etc
