### ISSUE TITLE
Contract page - update metadata

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#19]
The update metadata button on the contract page should update the docs accordion above it and the form displayed in the interact tab as well

![Screenshot 2021-06-09 at 20 12 20](https://user-images.githubusercontent.com/42985153/121417965-c1cbb000-c96a-11eb-9cb0-a39b95a00feb.png)

**Comment by statictype** [comment]
what are the exact use cases where someone wants to update the metadata of a deployed contract?

**Comment by statictype** [comment]
@Robbepop @cmichi please see the above question

**Comment by cmichi** [comment]
> what are the exact use cases where someone wants to update the metadata of a deployed contract?

@statictype The use-case is the proxy pattern, which enables upgradable contracts. Consider this example: 

* You deploy a `proxy` contract, this contract contains the address of another contract in it's storage.
* This `proxy` contract exposes one `update_address` message: an admin can update this storage item with the address of some contract.
* Any other message call to the `proxy` contract (besides `update_address`)  is forwarded to the stored contract address.
* Users use the proxy contract with the metadata of this stored contract address. So for them it's invisible that they actually call the proxy contract first.
* In case an admin updates the address of the contract where calls are forwarded to, the metadata which users use to interact with the `proxy` contract might change.

Does this clarify things?
