### ISSUE TITLE
New contract not saved in db

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#194]
Upload flipper using the [hosted version](https://paritytech.github.io/substrate-contracts-explorer/#/instantiate/new)
It works the first time, but the following times it fails because of a db error. Although the UI displays the salt as off, it is actually on so the instantiation succeeds on-chain, but the contract isn't stored in db so the redirect to the contract page doesn't happen 

<img width="1434" alt="Screenshot 2022-02-03 at 11 47 39" src="https://user-images.githubusercontent.com/42985153/152330573-e8964bce-4db4-4fe7-991b-1ed1e5f52874.png">

**Comment by statictype** [comment]
this happens because local storage is not cleared when db is deleted, i think

**Comment by achimcc** [comment]
Im running into the same issues when trying to instantiate more then one contract. Especially, the following doesn't work for me after starting a fresh local node:

- instantiate `Contract-Transfer` from `Alice` account
- then trying to instantiate `Flipper` from `Alice` account

Trying an incognito tab didn't resolve this bug. Looks like this should have really top priority right now?

**Comment by statictype** [comment]
this was confirmed to be a problem on the ThreadDb side. there is a PR to fix it but hasn't been merged yet 
https://github.com/textileio/js-textile/pull/1218#issuecomment-1054491892
