### ISSUE TITLE
Remove trailing zeros

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#238]
On the Interact page we show 
![Screenshot 2022-03-14 at 09 35 26](https://user-images.githubusercontent.com/42985153/158136841-04b65044-3ffc-4b0b-b1d1-f06556bce2b6.png)

**Comment by athei** [comment]
Why is there a decimal point for an integer number anyways? I assume that you format the raw integer output to the "chain currency". I am wondering how you detect that this `u128` is supposed to be currency.

**Comment by statictype** [comment]
we're not getting the correct types apparently, it's supposed to be `Balance` if I look in the `erc20` meta
this issue is a follow up of https://github.com/paritytech/contracts-ui/pull/209 which also lets users pass decimal values in `Balance` inputs. 
so, you're saying we shouldn't allow decimals at all?

**Comment by athei** [comment]
> so, you're saying we shouldn't allow decimals at all?

No. It makes sense for legibility to use decimals. What I am saying is that you should make it clear that you formatted the raw output to some other representation: Show the unit you formatted it to. It maybe even be a good idea to show both values in case you formatted it: The raw value and then the formatting into the currency. You can get the currency symbol by calling the `system_properties` RPC:

<img width="1080" alt="Screenshot 2022-03-14 at 11 08 28" src="https://user-images.githubusercontent.com/2580396/158150978-6f629f7e-76c6-4f11-8d86-9aa59598b465.png">
