### ISSUE TITLE
Settings page - custom endpoint

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#263]
Implement the custom endpoint input on the Settings page. It should only accept [valid](https://github.com/paritytech/contracts-ui/blob/89379cff83ca672172109f88f794a506160e2ebf/src/api/util/index.ts#L104) ws urls
Related to https://github.com/paritytech/contracts-ui/issues/141

Probably needs a save button next to the input. When the user adds a custom endpoint, it should be used by the local node option in the chain select dropdown in the sidebar. On subsequent visits to the settings page, the input should be filled with the custom endpoint

![Screenshot 2022-03-24 at 12 17 49](https://user-images.githubusercontent.com/42985153/159905411-ba0da6e7-4c81-4d45-8d77-7ed7a6f73255.png)

**Comment by gabrielfior** [comment]
Happy to try solving this issue @statictype
