### ISSUE TITLE
App breaks if extension is not installed

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#305]
**To Reproduce**

1. Start the app in a browser where the Polkadot extension is not installed. 
2. Connect to Contracts on Rococo
3. Go to` /instantiate`
4. Page tries to get keyring accounts to render the `AccountSelect`, but a white screen is displayed because the keyring is not initialised

**Expected behavior**
The app should check the Polkadot extension is installed and if it's not, display a modal. The user should import or create a Substrate account before using the app

Connect Modal
![Connect Modal](https://user-images.githubusercontent.com/42985153/169500241-df99be91-7a77-4fef-bdaf-8703ec9e8a0d.png)

**Comment by kwingram25** [comment]
The app no longer appears to break without an extension installed. Still should display a modal however.
![Screenshot from 2022-06-22 11-21-13](https://user-images.githubusercontent.com/879755/175109148-16d03bcd-61a9-4387-9924-5f457236887f.jpg)

**Comment by statictype** [comment]
if you follow the steps described in the issue, you can see that it does

<img width="1437" alt="Screenshot 2022-06-23 at 08 04 49" src="https://user-images.githubusercontent.com/42985153/175226992-ef764c17-a010-4bd5-ba0d-0fe641b5a537.png">

**Comment by shunsukew** [comment]
Even if polkadot.js is properly installed, white screen will be displayed when website is disabled at "Manage Website Access". I think information to guide users to enable it should be displayed.
<img width="562" alt="Screen Shot 2022-07-12 at 0 35 31" src="https://user-images.githubusercontent.com/28953860/178302491-0afa2e9f-6038-40f2-a9ac-0a9a15097639.png">

**Comment by statictype** [comment]
thanks, @shunsukew! took this into account in https://github.com/paritytech/contracts-ui/pull/335
