### ISSUE TITLE
Contract messages with AccountId as args have multiple input fields

### ISSUE THREAD

**Issue by DoubleOTheven** [paritytech/contracts-ui#367]
**Describe the bug**
See image.

**To Reproduce**

This function generates the UI seen in the screenshot

```rs
        type PlayerId = AccountId;
        
        #[ink(message)]
        pub fn register_player(&mut self, id: PlayerId) {
            // ... code
        }
```

**Expected behavior**
There should be a single input field for the UI as it is on https://polkadot.js.org/apps/#/contracts

**Screenshots**
<img width="993" alt="Screen Shot 2022-09-30 at 12 39 24 PM" src="https://user-images.githubusercontent.com/2101499/193317266-49faef25-e1d8-447d-8010-0e64e8a54d05.png">

**Desktop (please complete the following information):**
 - Browser Firefox

**Comment by athei** [comment]
I think this are a actually two issues:

1. Yes. A array or vector of `u8` should display as hex input as in polkadot.js right now.
2. But this should be an `AccountId` and used to render as a list of knows accounts. The reason for this not happening are probably two:
    - You hide your type behind a useless typedef. Please remove. Rationale: https://github.com/paritytech/ink-workshop/pull/4#discussion_r982632381
    - Changes in ink! broke this features. Fixed in https://github.com/polkadot-js/api/pull/5237 but not yet released.

**Comment by statictype** [comment]
this was fixed with https://github.com/polkadot-js/api/pull/5237
