### ISSUE TITLE
Not compatible with `polkadot-v0.9.31` and later Substrate

### ISSUE THREAD

**Issue by jasl** [paritytech/contracts-ui#371]
Trying `contracts-ui` with Substrate Node `polkadot-v0.9.31` and later will lead node runtime panic, probably relates to https://github.com/paritytech/substrate/pull/12429

I already created an issue for Substrate https://github.com/paritytech/substrate/issues/12548

**Comment by athei** [comment]
Supported for this was added in polkadot.js:
https://github.com/polkadot-js/api/blob/master/CHANGELOG.md#951-oct-8-2022

**Comment by jasl** [comment]
> Supported for this is already in polkadot.js: https://github.com/polkadot-js/api/blob/master/CHANGELOG.md#951-oct-8-2022

So conracts-ui just need to upgrade polkadot.js dependency? I tried master branch it's also failed.

**Comment by statictype** [comment]
It might me more than just an upgrade, this is a major breaking change. Not clear if polkadot.js/api supports `Weightv2` for runtime calls and RPCs or only for transactions and how it handles backward compatibility. Will look into it asap.

**Comment by statictype** [comment]
@jasl there is no easy way to do this without breaking older nodes. will have to display a new input if the node supports WeightV2 and also encode/decode dry run results differently depending if the node supports V1, V2 or V1,5.
Most likely will have this early next week (on holiday atm)

**Comment by jasl** [comment]
> @jasl there is no easy way to do this without breaking older nodes. will have to display a new input if the node supports WeightV2 and also encode/decode dry run results differently depending if the node supports V1, V2 or V1,5. Most likely will have this early next week (on holiday atm)

Understood, no rush, Polkadot v0.9.31 release should 3 weeks later

**Comment by jasl** [comment]
https://github.com/polkadot-js/api/releases/tag/v9.8.1 is released!

Note: I PR Substrate for marking contracts API `api_version(2)`, I backported to `0.9.33` and `0.9.32` only, `0.9.31` is released before the PR, so people may experience bug behavior.
