### ISSUE TITLE
Shows "Unsuported node version" when trying to connect

### ISSUE THREAD

**Issue by erasmus** [paritytech/contracts-ui#375]
**Describe the bug**
Shows: "Unsuported node version" when trying to connect

**To Reproduce**
1. Go to https://contracts-ui.substrate.io/?rpc=wss://rococo-contracts-rpc.polkadot.io
2. Error message is shown in popup

**Expected behavior**
Canvas UI loads and is available for input

**Screenshots**
![image](https://user-images.githubusercontent.com/1915920/203525331-6343bc61-dc88-45d0-a5ba-09cb0d51d85b.png)

**Desktop (please complete the following information):**
 - Browser Chrome/Brave

**Comment by wottpal** [comment]
Try using this version insead: https://weightv1--contracts-ui.netlify.app/?rpc=wss://rococo-contracts-rpc.polkadot.io

It's for chains that are still running WeightsV1. (Don't know if that's the case for rococo, but it seems to work!)

**Comment by athei** [comment]
Rococo still runs WeightV1. So you need to use the older version of ContractsUI as suggested by the error message. This is not a bug.

**Comment by statictype** [comment]
@erasmus if you click on the link in the popup, you will be taken to an older version which works as expected

**Comment by athei** [comment]
Just upgraded rococo. It works now with the normal contracts ui.
