### ISSUE TITLE
Getting address not valid error when trying to add contract on address.

### ISSUE THREAD

**Issue by niklabh** [paritytech/contracts-ui#389]
**Describe the bug**
Getting address not valid error when trying to add contract on address.
Chain: Shibuya
Contract address: XvGYmchDETWtqy5fFnL6hW3c4oi2RaKs3XogMJ9Nj6heKGo
![Screenshot from 2023-01-05 11-13-51](https://user-images.githubusercontent.com/874046/210756118-6dad9c5b-2278-41a4-89ca-9e3ff7f0f50a.png)
Same address is working on polkadot js

**To Reproduce**
1. Go to https://contracts-ui.substrate.io/address-lookup
2. Enter address XvGYmchDETWtqy5fFnL6hW3c4oi2RaKs3XogMJ9Nj6heKGo

**Expected behavior**
It should be able to add address without error

**Comment by statictype** [comment]
Thanks for reporting this @niklabh! I added a more reliable fix just now
