### ISSUE TITLE
 Cannot read properties of undefined (reading 'instantiate')

### ISSUE THREAD

**Issue by theHardCoder05** [paritytech/contracts-ui#392]
**Describe the bug**

**To Reproduce**
1. GO TO https://contracts-ui.substrate.io -> upload a new SC
2. GO TO https://contracts-ui.substrate.io/instantiate. You will see the error in developer tool mode.

**Expected behavior**

**Screenshots**
Please see the attached screenshot below.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by theHardCoder05** [comment]
![Uploading Screenshot 2023-01-08 at 11.52.29.png…]()

**Comment by statictype** [comment]
can't reproduce this behaviour. what contract did you use and on which chain were you trying to upload?

**Comment by theHardCoder05** [comment]
[flipper.contract.zip](https://github.com/paritytech/contracts-ui/files/10377667/flipper.contract.zip)
Hi, I have attached my Smart Contract file here in Zip format.

**Comment by statictype** [comment]
please upload the contract on Github and post the link to the repo here. will not download a random zip file :)

**Comment by theHardCoder05** [comment]
@statictype - I tried. Unfornately, the extension of the file is not supported here in Github. Any thought?

**Comment by athei** [comment]
I think what is meant here is post a link to the source code repo. And make sure to declare which versions of everything you are using to build the contract (cargo-contract, node, Rust) in the README.

**Comment by statictype** [comment]
yes! :)

**Comment by statictype** [comment]
closed for lack of activity. please reopen if the problem persists.
