### ISSUE TITLE
Issue with api runtime contexts

### ISSUE THREAD

**Issue by EdinyangaOttoho** [paritytech/contracts-ui#399]
**Describe the bug**
When using the new ContractPromise for the Aleph Zero chain, I get an error:
```bash
Your runtime does not expose the api.call.contractsApi.call runtime interfaces
```

**To Reproduce**

1. Create an API provider:
```bash
wsProvider = new WsProvider('wss://ws.test.azero.dev')
api = await ApiPromise.create({ provider: wsProvider })
```
2. Try using the metadata and address of a token to create an instance of a contract:
```bash
const contract = new ContractPromise(api, contract_metadata, contract_address)
```
3. Error shows up:
```bash
Uncaught (in promise) Error: Your runtime does not expose the api.call.contractsApi.call runtime interfaces
```

**Expected behavior**
It is supposed to create an instance of the contract that will allow for contract.tx and contract.query methods.

**Screenshots**
![image](https://user-images.githubusercontent.com/45470783/213878965-ae560671-bd52-4e0c-a655-392d59b2f6ab.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 89

**Environment (please complete the following information where it makes sense):**

- contract version: ink! v4.0.0-beta
- cargo-contract: 2.0.0-rc
- Contracts on Aleph Zero Testnet
- rust toolchain: nightly-x86_64-unknown-linux-gnu
- rustc 1.64.0-nightly

**Comment by statictype** [comment]
this is unrelated to Contracts UI. 
the error suggests you are connected to an older node that doesn't expose the contracts runtime api (which is not the case for Aleph Zero Testnet) or that your `@polkadot/api` version is too old perhaps. the bug is most likely in your code, i suggest posting a reproducible sample on [Substrate StackExchange](https://substrate.stackexchange.com/questions/tagged/polkadot-js) and get help from the community.

**Comment by EdinyangaOttoho** [comment]
My polkadot.js version was a newer one and wasn't compatible with the current release (with an older version). What I rather did was downgrade it to 9.11.x and the rest was history.

Also, I modified my code to support Weights V2 to support refTimeLimit, proofSize, storageDepositLimit etc, which are the new fields needed for Aleph Zero Testnet ink! 4
