### ISSUE TITLE
Can't connect to local node in Safari when using deployed app

### ISSUE THREAD

**Issue by cmichi** [paritytech/contracts-ui#400]
**Describe the bug**
Opening https://contracts-ui.substrate.io/ in Safari 16.2 and selecting "Local Node" results in a JavaScript error and the site not loading:

<img width="1153" alt="Bildschirm­foto 2023-01-24 um 08 30 49" src="https://user-images.githubusercontent.com/241530/214235188-4c452137-9511-4522-9df4-46706326ae5f.png">

**Expected behavior**
The site should either load or display a note that it doesn't work in Safari.

**Desktop:**

- OS: macOS Ventura 13.1
- Browser Safari
- Version 16.2

**Comment by statictype** [comment]
We don't really support Safari indeed. It goes out of its way to block insecure content so connecting to a non-secure WebSocket endpoint from a secure origin is not really possible and there are no signer extensions available (to my knowledge)
If you really need to use Safari with a dev node I suggest running Contracts UI locally as described [here](https://github.com/paritytech/contracts-ui#run-the-app-locally) 
Will add a user warning asap.

**Comment by athei** [comment]
Safari sticks closer to the WebSocket standard which disallows this behaviour. There is no way for contracts ui to fix this.
