### ISSUE TITLE
Better Input for Fixed-Length Arrays (`[T, N]`) 

### ISSUE THREAD

**Issue by ashutoshvarma** [paritytech/contracts-ui#416]
**Is your feature request related to a problem? Please describe.**
When inputting a fixed length array like a `[u8;20]` (an EVM Address), it is frustrating and not practical enough to input each `u8` separately.

**Describe the solution you'd like**
For fixed length bytes array, input should also provide option to input hex-encoded strings, like polkadot-js provides.

**Additional context**
![image](https://user-images.githubusercontent.com/17181457/221480147-07e93ba8-0184-4e76-9e39-1f859a666d11.png)

**Comment by PierreOssun** [comment]
Any update on it ? @statictype

**Comment by statictype** [comment]
can you please provide a contract to test against?

**Comment by peetzweg** [comment]
For sure this is nice ux improvement. IMHO not too sure to completely drop the the current ux to enter array elements.

I'm not too available this week but could try to fit it in next weeks.
However, how do you @ashutoshvarma or @PierreOssun work on a PR for this? Shouldn't be too complex for what I know.

**Comment by Maar-io** [comment]
Hi there, any update on this? This makes it almost impossible to use `eth_addresses` as input.
We use ethereum addresses on Astar's cross VM feature.

**Comment by peetzweg** [comment]
> Hi there, any update on this? This makes it almost impossible to use `eth_addresses` as input. We use ethereum addresses on Astar's cross VM feature.
@Maar-io 
Isn't this just a user experience issue? Because it's cumbersome to click the `+` button for new array elements? Or can you describe in other words what your issue is?

**Comment by Maar-io** [comment]
> @Maar-io Isn't this just a user experience issue? Because it's cumbersome to click the `+` button for new array elements? Or can you describe in other words what your issue is?

You can call it bad UX but it is really not usable. Instead of copy and paste EVM user/contract address, you need to manually enter 20 bytes, one by one.
This is how it looks on Polkadot.js
<img width="891" alt="Screenshot 2023-05-04 at 10 35 52" src="https://user-images.githubusercontent.com/34627453/236153143-6ffa6cad-5c3e-4c59-9998-f2ebcc6ff5c8.png">

**Comment by statictype** [comment]
I can pick this up next week

**Comment by Maar-io** [comment]
Hello friend, any update on this?
I see you implemented hash input (64 chars)
The H160 should be similar as feature
