### ISSUE TITLE
Display non-String-ified types in Outcome

### ISSUE THREAD

**Issue by cmichi** [paritytech/contracts-ui#421]
I return a `Vec<Player>` from a contract. `Player` looks like this:
```rust
    pub struct Player {
        pub id: AccountId,
        pub name: String,
        pub gas_used: u64,
        pub score: u64,
    }
```

The UI displays this though:

![screenshot-contracts-ui substrate io-2023 03 03-19_05_55](https://user-images.githubusercontent.com/241530/222794946-8a137cd2-734a-4e43-aab2-da5937fe5e61.png)

It would be great to have the actual types reflected there and not their `String` representation. So e.g. for `gas_used` and `score` a `Number`. It's harder to debug stuff because this displayed representation is not what is actually returned,

**Comment by peetzweg** [comment]
Resolved in #441.
