### ISSUE TITLE
Allow users to copy the code hash of the contract

### ISSUE THREAD

**Issue by buraktabn** [paritytech/contracts-ui#427]
**Is your feature request related to a problem? Please describe.**
I can't copy the code hash of the contract.  I can see the partial code hash under "Add New Contract > Use On-Chain Contract Code".

**Describe the solution you'd like**
The contract page should show the code hash and allow copying easily.

**Describe alternatives you've considered**
I have to call the chain store of the contract pallet in order to obtain the code hash of my contract.

**Comment by statictype** [comment]
@buraktabn i agree we need a better way to handle this, but as a quick workaround you can copy the code hash from the URL during the re-instantiation process
