### ISSUE TITLE
Add support for Peaq Agung

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#446]
**Describe the bug**
Instantiating contracts on Peak Agung breaks the UI. 

```
TypeError: Cannot read properties of undefined (reading 'isErr')
```

**To Reproduce**

1. Go to https://weightv1--contracts-ui.netlify.app/?rpc=wss://wss.agung.peaq.network
2. Instantiate [sbp.contract.zip](https://github.com/paritytech/contracts-ui/files/11019880/sbp.contract.zip)
3. See breaking error when navigating to step 2 

**Expected behavior**
The contract instantiation for this old contract should work, tested on [Apps](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.agung.peaq.network#/contracts)
For newer contracts the dry-run is expected to fail with `CodeRejected` so instantiation should not be possible.

To do:
- [ ] remove the testnet until the issue is fixed
- [ ] fix the problem and re-add the test net

**Comment by peetzweg** [comment]
`Peaq Agung` seems still to be running and still using weightV1. Looking into this issue it stems from this "dry run" here:
https://github.com/paritytech/contracts-ui/blob/7986deca6956d0453c368f8843b0c9d500cfabb6/src/ui/components/instantiate/Step2.tsx#L89-L98

Despite the type hinting the `result` beeing `ContractInstantiateResult` containing `gasConsumed` it's just the inner `InstantiateReturnValue`. Not sure why the actual `Result` containing the missing `gasConsumed` and `gasRequired` is missing. Might be a combination of node software and pjs version?

```ts

/** @name ContractInstantiateResult */
export interface ContractInstantiateResult extends Struct {
    readonly gasConsumed: u64;
    readonly gasRequired: u64;
    readonly storageDeposit: StorageDeposit;
    readonly debugMessage: Text;
    readonly result: InstantiateReturnValue;
}

/** @name InstantiateReturnValue */
export interface InstantiateReturnValue extends Result<InstantiateReturnValueOk, DispatchError> {
    readonly isErr: boolean;
    readonly asErr: DispatchError;
    readonly isOk: boolean;
    readonly asOk: InstantiateReturnValueOk;
}
```

Is this worth further investigation or should we just drop support for WeightsV1 @cmichi ?

**Comment by cmichi** [comment]
@peetzweg Let's drop support for WeightsV1. Can you take care of it?

**Comment by peetzweg** [comment]
`contracts-ui` dropped support for a `WeightsV1` version today.
