### ISSUE TITLE
Mismatch of error message and selected network

### ISSUE THREAD

**Issue by cmichi** [paritytech/contracts-ui#452]
I opened this URL: https://contracts-ui.substrate.io/add-contract.

This is what I saw:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/241530/227981816-c82adc92-598c-4b2b-bea5-8fcb3f8a94af.png">

Notice the mismatch in the dropdown left (Astar network) and the error message (127.0.0.1).

**Comment by gaboesquivel** [comment]
![image](https://github.com/paritytech/contracts-ui/assets/391270/977c6525-3e71-40ce-9d55-cb0a5ac471a8)
I'm unable to replicate this issue

**Comment by peetzweg** [comment]
Most likely a `LocalStorage` ui mismatch which should resolve itself once a network is selected. I wasn't able to replicate this. Happy to reopen this if we find a way.
