### ISSUE TITLE
Re-use metadata when adding contract

### ISSUE THREAD

**Issue by wottpal** [paritytech/contracts-ui#464]
It would be awesome if when I "Add contract from address", it would be possible to re-use uploaded `matadata.json` from previously added contracts with just a click.

cc @statictype

**Comment by peetzweg** [comment]
So in addition to the option of uploading a new metadata.json, offering a dropdown of already used metadata json. Sounds helpful to me. 👍 

<img width="480" alt="SCR-20230419-kkck" src="https://user-images.githubusercontent.com/839848/233032237-fcf5fa97-6e9a-450c-9d8a-ec898fd0facb.png">

**Comment by statictype** [comment]
would be a nice UX improvement but we have other priorities atm. why would users have the need to attach the same metadata to different addresses? doesn't sound like something that comes up too often
as for UI, we could reuse the code hashes [list](https://user-images.githubusercontent.com/839848/225915100-ab730ce4-547f-4c45-b779-022d86537278.gif)

**Comment by wottpal** [comment]
happens to me many times on a daily basis during development when re-deploying the same contract (let it be because of test stuits running or the frontend needs a fresh start etc.)

**Comment by peetzweg** [comment]
@wottpal does #454 resolves this issue for you as intended?

**Comment by wottpal** [comment]
> @wottpal does #454 resolves this issue for you as intended?

Yes great, big improvement. 🚀
You probably mean #545, though :P
