### ISSUE TITLE
Syntax Highlighting Missing in Light Theme

### ISSUE THREAD

**Issue by peetzweg** [paritytech/contracts-ui#487]
**Describe the bug**
Contract message names and constructors are highlighted in the dark theme, however this is not the case for the light theme. This issue is present throughout the contract-ui app.

 

**To Reproduce**
Instantiate a new contract and see the difference in the display of the function names in light/dark theme.

**Expected behavior**
Both themes should highlight message/constructor names the same way.

**Screenshots**

<img width="760" alt="Screenshot 2023-06-19 at 10 27 02" src="https://github.com/paritytech/contracts-ui/assets/839848/51160876-4487-45d9-8ad7-a027c634f223">

<img width="760" alt="Screenshot 2023-06-19 at 10 27 08" src="https://github.com/paritytech/contracts-ui/assets/839848/fd6ad457-3ed1-4a56-93c4-8095004cfc68">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Firefox
- Version latest

**Comment by statictype** [comment]
closed in https://github.com/paritytech/contracts-ui/pull/490
