### ISSUE TITLE
Support `AccountId20`

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/contracts-ui#492]
**Is your feature request related to a problem? Please describe.**
I'm working on a chain that uses the `AccountId20` type. This is the ethereum-style accounts. The contracts UI, still injects the standard Substrate style dev accounts.

**Describe the solution you'd like**
I would like the UI to detect that I am using an ethereum chain and insert the right accounts accordingly. Polkadot JS Apps does this.

**Describe alternatives you've considered**
If auto-detecting isn't feasible, a manual setting would be perfectly fine as well.

**Additional context**
The main thing to realize is that the keyring itself already supports this. You just have to create it with `type: 'ethereum'`.

**Comment by JoshOrndorff** [comment]
I've got a demonstration of how to solve this in https://github.com/paritytech/contracts-ui/pull/493. I would just need a little help from a project maintainer about how to expose this as a proper option to users.

**Comment by statictype** [comment]
closed in https://github.com/paritytech/contracts-ui/pull/493
