### ISSUE TITLE
Instantiate dry-run doesn't catch the reversion

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#494]
Trying to upload a contract with the wrong metadata should result in a failed dry-run, however the dry run is successful and the instantiation fails

```
CONTRACTS.ContractReverted: The contract ran to completion but decided to revert its storage changes.,Please note that this error is only returned from extrinsics. When called directly,or via RPC an `Ok` will be returned. In this case the caller needs to inspect the flags,to determine whether a reversion has taken place.
```
Similarly to the call dry-run, the results should be decoded and shown to the user.

https://github.com/paritytech/contracts-ui/blob/master/src/helpers/output.ts

**Comment by gaboesquivel** [comment]
I run several tests and found out that `source`, `spec.constructors`, `types`, `version` are the only values required and verified before calling contract api `instantiate` to get dry run results.  No other metadata is being checked or validated, In my case I don't get a `ContractReverted` error, the deployment is successful ui is not able to detect how to interact with the contract. dryRun call doesn't throw any error either. 

Do we want to add further metadata at the ui level? it seems that api endpoints wont complaint about malformatted metadata in some cases.
