### ISSUE TITLE
contracts-ui should not inspect the code contained in a contracts bundle

### ISSUE THREAD

**Issue by athei** [paritytech/contracts-ui#507]
I am currently working on supporting RISC-V contracts (as opposed to wasm). I can produce a contract bundle that contains RISC-V instead of wasm code and feed that into contracts UI. I am connected to a dev node that can run RISC-V contracts on pallet-contracts.

I get past the dry-run but when I submit the instantatiation the screen is white and there is an error on the console "Error: No WASM code provided".

Expected behaviour: The UI does not inspect, touch or care about the code. It just passes it along as data to the node.

Behaviour I  am seeing: The UI errors out because it determines that the code is not wasm.

**Comment by statictype** [comment]
I removed the pre-instantiation WASM checks a while ago, but didn't have a RISC-V contract to test further.
The error you encountered is not thrown by the UI but polkadot.js (see this line [here](https://github.com/polkadot-js/api/blob/319535a1e938e89522ff18ef2d1cef66a5af597c/packages/api-contract/src/base/Code.ts#L52)) so for RISC-V contracts to work, we need to update the pjs api.

**Comment by peetzweg** [comment]
As `contracts-ui` is built ontop of `@polkadot/api-contract` we are a bit limited to what we can and cannot do. It is still checked but it now allows for these two different ELF headers.

https://github.com/polkadot-js/common/blob/f55e88c1167b243f6e2ce961e75d3e99ed3e78bc/packages/util/src/is/riscv.ts#L7-L11
