### ISSUE TITLE
Incorrect decoded return value of type Vec<(i16,i16)>

### ISSUE THREAD

**Issue by DoubleOTheven** [paritytech/contracts-ui#508]
**Describe the bug**

Incorrect values when decoding return value of type Vec<(i16,i16)>. (Vec<(u16,u16)> works just fine).

Issue was posted [here](https://github.com/paritytech/useink/issues/105), but also mentions Contracts UI.

**Comment by peetzweg** [comment]
Fix WIP https://github.com/polkadot-js/common/pull/1867

**Comment by peetzweg** [comment]
The underlying bug for this issue has been resolved and fixed all the way up to @polkadotjs/api. However, a new version of the package is not yet release so we can't upgrade `contracts-ui` to it yet. We will do so as soon as possible.

https://github.com/polkadot-js/api/issues/5702
