### ISSUE TITLE
Option<bool> does not work when value is false

### ISSUE THREAD

**Issue by Steven-Chang** [paritytech/contracts-ui#517]
**Describe the bug**
Option<bool> does not work when value is false

![Screenshot 2023-09-15 at 9 50 05 am](https://github.com/paritytech/contracts-ui/assets/14280689/b3424468-85e5-4ad8-9684-6e14a2eb4930)

**To Reproduce**

1. Go to ['https://contracts-ui.substrate.io/?rpc=wss://ws.test.azero.dev'](https://contracts-ui.substrate.io/?rpc=wss://ws.test.azero.dev)
2. Click on 'Add new contract'
3. Click on 'Use on chain contract address'
4. Paste in address input '5C6uExVKN4HtRXmmTZexzfRDEoKnRuDa6zEYQ445Sw8AnRGH'
6. Download Metadata from ['https://res.cloudinary.com/hv5cxagki/raw/upload/v1694690121/abis/aleph_zero/az_groups_bdrmyz.json'](https://res.cloudinary.com/hv5cxagki/raw/upload/v1694690121/abis/aleph_zero/az_groups_bdrmyz.json)
7. Enter Contract Name 'Groups', upload Metadata and click 'Next' button
8. Get TZERO from ['faucet'](https://faucet-smartnet.test.azero.dev/)
9. Create group via function 'groupsCreate'
10. Try to update group enabled status to false via function 'groupsUpdate'

**Expected behavior**
Group enabled to change to false.

**Desktop (please complete the following information):**

- Mac
- Brave Browser

**Environment (please complete the following information where it makes sense):**

- contract version: ink! 4.2.1
- cargo-contract version: 2.0.1
- chain name or dev node version: Aleph Zero Testnet
- rust toolchain: nightly-2023-02-01
- rustc version: 1.69.0-nightly

**Comment by statictype** [comment]
the form on the left doesn't reflect the contract value. that dropdown is just a form element wich displays options alphabetically
the contract value is displayed here

<img width="1192" alt="Screenshot 2023-09-15 at 06 51 11" src="https://github.com/paritytech/contracts-ui/assets/42985153/eae786ce-d261-40db-98c3-50468b0fdf95">

**Comment by Steven-Chang** [comment]
Hi @statictype, in your screenshot, you have set the value to false, but the result of the execution returns enabled: true.

**Comment by statictype** [comment]
i could reproduce the problem, you can't set the value to false

**Comment by Steven-Chang** [comment]
As a further note, I managed to set the value to false via a separate app.

**Comment by peetzweg** [comment]
@Steven-Chang thanks for reporting this. It's fixed now. 👍
