### ISSUE TITLE
Show contract's native token balance

### ISSUE THREAD

**Issue by wottpal** [paritytech/contracts-ui#521]
Just like in the Contracts-tab of polkadot.js/apps:

![CleanShot 2023-11-14 at 10 09 55@2x](https://github.com/paritytech/contracts-ui/assets/3930150/5a5422a9-65e3-4bfe-bd86-faa98372f897)

**Comment by peetzweg** [comment]
Got added in https://github.com/paritytech/contracts-ui/pull/530
